[package]
name = "proof-of-work"
version = "0.1.0"
authors = ["Dominik Rosser <dominik.rosser@protonmail.ch>"]

[dependencies]
rust-crypto = "^0.2"
num-bigint = "0.2"
num-traits = "0.2"
chrono = "0.4"
